/* This code was generated by Akka Serverless tooling.
 * As long as this file exists it will not be re-generated.
 * You are free to make changes to this file.
 */
package be.reaktika.weatherstation.domain.geocoding;

import org.junit.Test;

public class GeoCodingTest {

  @Test
  public void exampleTest() {
    //GeoCodingTestKit testKit = GeoCodingTestKit.of(GeoCoding::new);
    // use the testkit to execute a command
    // of events emitted, or a final updated state:
    // ValueEntityResult<SomeResponse> result = testKit.someOperation(SomeRequest);
    // verify the response
    // SomeResponse actualResponse = result.getReply();
    // assertEquals(expectedResponse, actualResponse);
    // verify the final state after the command
    // assertEquals(expectedState, testKit.getState());
  }

  @Test
  public void registerDataTest() {
    //GeoCodingTestKit testKit = GeoCodingTestKit.of(GeoCoding::new);
    // ValueEntityResult<Empty> result = testKit.registerData(AddToAggregationCommand.newBuilder()...build());
  }

}
