/* This code was generated by Akka Serverless tooling.
 * As long as this file exists it will not be re-generated.
 * You are free to make changes to this file.
 */
package be.reaktika.weatherstation.view;

import be.reaktika.weatherstation.domain.aggregations.WeatherStationExtremesAggregation;
import com.akkaserverless.javasdk.view.ViewContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class WeatherStationExtremesView extends AbstractWeatherStationExtremesView {

  private final static Logger logger = LoggerFactory.getLogger(WeatherStationExtremesView.class);

  public WeatherStationExtremesView(ViewContext context) {}

  @Override
  public WeatherStationExtremesAggregation.WeatherStationExtremesState emptyState() {
    return WeatherStationExtremesAggregation.WeatherStationExtremesState.getDefaultInstance();
  }

  @Override
  public UpdateEffect<WeatherStationExtremesAggregation.WeatherStationExtremesState> updateAggregations(WeatherStationExtremesAggregation.WeatherStationExtremesState currentState, WeatherStationExtremesAggregation.WeatherStationExtremesState event) {
    return effects().updateState(event);
  }
}
