/* This code was generated by Akka Serverless tooling.
 * As long as this file exists it will not be re-generated.
 * You are free to make changes to this file.
 */
package be.reaktika.weatherstation.view;

import be.reaktika.weatherstation.domain.aggregations.WeatherStationExtremesAggregation;
import com.akkaserverless.javasdk.view.ViewContext;
import com.google.protobuf.Empty;

public class WeatherStationExtremesView extends AbstractWeatherStationExtremesView {

  public WeatherStationExtremesView(ViewContext context) {}

  @Override
  public WeatherStationExtremesAggregation.WeatherStationExtremesState emptyState() {
    throw new UnsupportedOperationException("Not implemented yet, replace with your empty view state");
  }

  @Override
  public UpdateEffect<WeatherStationExtremesAggregation.WeatherStationExtremesState> updateAggregations(
    WeatherStationExtremesAggregation.WeatherStationExtremesState state, WeatherStationExtremesAggregation.WeatherStationExtremesState weatherStationExtremesState) {
    throw new UnsupportedOperationException("Update handler for 'UpdateAggregations' not implemented yet");
  }
}
