/* This code was generated by Akka Serverless tooling.
 * As long as this file exists it will not be re-generated.
 * You are free to make changes to this file.
 */
package be.reaktika.weatherstation.view;

import be.reaktika.weatherstation.domain.WeatherStationDomain;
import com.akkaserverless.javasdk.view.ViewContext;

public class WeatherStationOverallAverageView extends AbstractWeatherStationOverallAverageView {

  public WeatherStationOverallAverageView(ViewContext context) {}

  @Override
  public WeatherStationAverageViewModel.WeatherStationOverallAverageState emptyState() {
    throw new UnsupportedOperationException("Not implemented yet, replace with your empty view state");
  }

  @Override
  public UpdateEffect<WeatherStationAverageViewModel.WeatherStationOverallAverageState> processStationRegistered(
    WeatherStationAverageViewModel.WeatherStationOverallAverageState state, WeatherStationDomain.StationRegistered stationRegistered) {
    throw new UnsupportedOperationException("Update handler for 'ProcessStationRegistered' not implemented yet");
  }
  @Override
  public UpdateEffect<WeatherStationAverageViewModel.WeatherStationOverallAverageState> processTemperatureAdded(
    WeatherStationAverageViewModel.WeatherStationOverallAverageState state, WeatherStationDomain.TemperaturesCelciusAdded temperaturesCelciusAdded) {
    throw new UnsupportedOperationException("Update handler for 'ProcessTemperatureAdded' not implemented yet");
  }
  @Override
  public UpdateEffect<WeatherStationAverageViewModel.WeatherStationOverallAverageState> processWindspeedAdded(
    WeatherStationAverageViewModel.WeatherStationOverallAverageState state, WeatherStationDomain.WindspeedsAdded windspeedsAdded) {
    throw new UnsupportedOperationException("Update handler for 'ProcessWindspeedAdded' not implemented yet");
  }
}
