/* This code was generated by Akka Serverless tooling.
 * As long as this file exists it will not be re-generated.
 * You are free to make changes to this file.
 */
package be.reaktika.weatherstation.domain;

import com.akkaserverless.javasdk.eventsourcedentity.EventSourcedEntity;
import com.akkaserverless.javasdk.eventsourcedentity.EventSourcedEntity.Effect;
import com.akkaserverless.javasdk.eventsourcedentity.EventSourcedEntityContext;
import com.google.protobuf.Empty;

/** An event sourced entity. */
public class WeatherStation extends AbstractWeatherStation {

  @SuppressWarnings("unused")
  private final String entityId;

  public WeatherStation(EventSourcedEntityContext context) {
    this.entityId = context.entityId();
  }

  @Override
  public WeatherStationDomain.WeatherStationState emptyState() {
    throw new UnsupportedOperationException("Not implemented yet, replace with your empty entity state");
  }

  @Override
  public Effect<Empty> registerStation(WeatherStationDomain.WeatherStationState currentState, WeatherStationDomain.StationRegistrationCommand stationRegistrationCommand) {
    return effects().error("The command handler for `RegisterStation` is not implemented, yet");
  }

  @Override
  public Effect<Empty> publishTemperatureReport(WeatherStationDomain.WeatherStationState currentState, WeatherStationDomain.StationTemperatureCommand stationTemperatureCommand) {
    return effects().error("The command handler for `PublishTemperatureReport` is not implemented, yet");
  }

  @Override
  public Effect<Empty> publishWindspeedReport(WeatherStationDomain.WeatherStationState currentState, WeatherStationDomain.StationWindspeedCommand stationWindspeedCommand) {
    return effects().error("The command handler for `PublishWindspeedReport` is not implemented, yet");
  }

  @Override
  public WeatherStationDomain.WeatherStationState stationRegistered(WeatherStationDomain.WeatherStationState currentState, WeatherStationDomain.StationRegistered stationRegistered) {
    throw new RuntimeException("The event handler for `StationRegistered` is not implemented, yet");
  }
  @Override
  public WeatherStationDomain.WeatherStationState temperaturesCelciusAdded(WeatherStationDomain.WeatherStationState currentState, WeatherStationDomain.TemperaturesCelciusAdded temperaturesCelciusAdded) {
    throw new RuntimeException("The event handler for `TemperaturesCelciusAdded` is not implemented, yet");
  }
  @Override
  public WeatherStationDomain.WeatherStationState windspeedsAdded(WeatherStationDomain.WeatherStationState currentState, WeatherStationDomain.WindspeedsAdded windspeedsAdded) {
    throw new RuntimeException("The event handler for `WindspeedsAdded` is not implemented, yet");
  }

}
