/* This code was generated by Akka Serverless tooling.
 * As long as this file exists it will not be re-generated.
 * You are free to make changes to this file.
 */
package be.reaktika.weatherstation.domain.aggregations;

import com.akkaserverless.javasdk.testkit.ValueEntityResult;
import com.akkaserverless.javasdk.valueentity.ValueEntity;
import com.google.protobuf.Empty;
import org.junit.Test;
import org.mockito.Mockito;

import static org.junit.Assert.*;

public class WeatherStationExtremesTest {



  @Test
  public void exampleTest() {
    WeatherStationExtremesTestKit testKit = WeatherStationExtremesTestKit.of(WeatherStationExtremes::new);
    // use the testkit to execute a command
    // of events emitted, or a final updated state:
    // ValueEntityResult<SomeResponse> result = testKit.someOperation(SomeRequest);
    // verify the response
    // SomeResponse actualResponse = result.getReply();
    // assertEquals(expectedResponse, actualResponse);
    // verify the final state after the command
    // assertEquals(expectedState, testKit.getState());
  }

  @Test
  public void registerDataTest() {
    WeatherStationExtremesTestKit testKit = WeatherStationExtremesTestKit.of(WeatherStationExtremes::new);
    // ValueEntityResult<Empty> result = testKit.registerData(AddToAggregationCommand.newBuilder()...build());
  }

}
