/* This code was generated by Akka Serverless tooling.
 * As long as this file exists it will not be re-generated.
 * You are free to make changes to this file.
 */
package be.reaktika.weatherstation.domain;

import be.reaktika.weatherstation.Main;
import com.akkaserverless.javasdk.testkit.junit.AkkaServerlessTestkitResource;
import com.google.protobuf.Empty;
import org.junit.ClassRule;
import org.junit.Test;

import static java.util.concurrent.TimeUnit.*;

// Example of an integration test calling our service via the Akka Serverless proxy
// Run all test classes ending with "IntegrationTest" using `mvn verify -Pit`
public class WeatherStationIntegrationTest {

  /**
   * The test kit starts both the service container and the Akka Serverless proxy.
   */
  @ClassRule
  public static final AkkaServerlessTestkitResource testkit =
    new AkkaServerlessTestkitResource(Main.createAkkaServerless());

  /**
   * Use the generated gRPC client to call the service through the Akka Serverless proxy.
   */
  private final WeatherStationEntityServiceClient client;

  public WeatherStationIntegrationTest() {
    client = WeatherStationEntityServiceClient.create(testkit.getGrpcClientSettings(), testkit.getActorSystem());
  }

  @Test
  public void registerStationOnNonExistingEntity() throws Exception {
    // TODO: set fields in command, and provide assertions to match replies
    // client.registerStation(WeatherStationDomain.StationRegistrationCommand.newBuilder().build())
    //         .toCompletableFuture().get(2, SECONDS);
  }

  @Test
  public void publishTemperatureReportOnNonExistingEntity() throws Exception {
    // TODO: set fields in command, and provide assertions to match replies
    // client.publishTemperatureReport(WeatherStationDomain.StationTemperatureCommand.newBuilder().build())
    //         .toCompletableFuture().get(2, SECONDS);
  }

  @Test
  public void publishWindspeedReportOnNonExistingEntity() throws Exception {
    // TODO: set fields in command, and provide assertions to match replies
    // client.publishWindspeedReport(WeatherStationDomain.StationWindspeedCommand.newBuilder().build())
    //         .toCompletableFuture().get(2, SECONDS);
  }
}
